-- drwasiullah.com content database (Cloudflare D1 = SQLite). Phase 1 of docs/admin-portal-spec.md.
-- Design: each row keeps the exact original JSON object in `data` (so nothing is lost and the site's data files can be
-- regenerated byte for byte) plus a few real columns for querying, ordering and visibility. Later phases promote more
-- fields to columns as the admin portal needs them.
-- `origin` says which data file a row belongs to (catalogue | library | makkah | haram); `pos` is its position there.
-- `status`: published rows are shipped to the site; draft/hidden rows are kept but never exported for the build.

CREATE TABLE IF NOT EXISTS series (
  id      TEXT PRIMARY KEY,
  origin  TEXT NOT NULL,
  pos     INTEGER NOT NULL,
  sec     TEXT,
  title   TEXT NOT NULL,
  status  TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft','published','hidden')),
  data    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS series_origin_pos ON series (origin, pos);

CREATE TABLE IF NOT EXISTS lessons (
  id        TEXT PRIMARY KEY,
  origin    TEXT NOT NULL,
  pos       INTEGER NOT NULL,
  series_id TEXT,
  kind      TEXT,                       -- audio | video | NULL
  n         INTEGER,                    -- lesson number inside the series
  section   TEXT,
  status    TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft','published','hidden')),
  data      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS lessons_origin_pos ON lessons (origin, pos);
CREATE INDEX IF NOT EXISTS lessons_series_n   ON lessons (series_id, n);

CREATE TABLE IF NOT EXISTS books (
  id      TEXT PRIMARY KEY,
  origin  TEXT NOT NULL,
  pos     INTEGER NOT NULL,
  title   TEXT NOT NULL,
  status  TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft','published','hidden')),
  data    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS books_origin_pos ON books (origin, pos);

-- mirrored-media manifest: original URL -> our copy on media.drwasiullah.com
CREATE TABLE IF NOT EXISTS media (
  src  TEXT PRIMARY KEY,
  pos  INTEGER NOT NULL,
  data TEXT NOT NULL
);

-- whole documents that are not lists of rows: catalogue meta, schedule, bio
CREATE TABLE IF NOT EXISTS docs (
  name TEXT PRIMARY KEY,
  data TEXT NOT NULL
);

-- how each data file is laid out, so the export is byte-identical to what is in git
CREATE TABLE IF NOT EXISTS files (
  name        TEXT PRIMARY KEY,         -- e.g. data/library.json
  indent      INTEGER,                  -- NULL = minified
  trailing_nl INTEGER NOT NULL DEFAULT 0,
  keys        TEXT NOT NULL             -- JSON array: top-level key order
);

-- phase 2 (empty for now). NEVER exported to git: the repository is public.
CREATE TABLE IF NOT EXISTS users (
  email      TEXT PRIMARY KEY,
  role       TEXT NOT NULL CHECK (role IN ('admin','editor')),
  name       TEXT,
  active     INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE TABLE IF NOT EXISTS audit_log (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  at        TEXT NOT NULL DEFAULT (datetime('now')),
  actor     TEXT NOT NULL,
  action    TEXT NOT NULL,
  entity    TEXT NOT NULL,
  entity_id TEXT,
  before    TEXT,
  after     TEXT
);
