#!/usr/bin/env node
/* Content database tool (Cloudflare D1 = SQLite). Phase 1 of docs/admin-portal-spec.md. No dependencies (Node 22 `node:sqlite`).

   node scripts/db.mjs seed   [--site site] [--out db/seed.sql]     site data files -> SQL that fills an EMPTY or existing D1 (it clears the content tables first)
   node scripts/db.mjs export --out DIR [--from-sql dump.sql | --db file.sqlite] [--all]
                                                                    database -> the same data files (published rows only, unless --all)
   node scripts/db.mjs verify [--site site]                         seed -> scratch database -> export -> byte-compare with the files in git

   `export --from-sql` reads the dump written by `wrangler d1 export`, so the same code serves the nightly backup and (later) Publish. */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const MIGRATIONS = path.join(ROOT, "db", "migrations");

/* which data file holds what. `lists`: top-level arrays stored as rows; `rows` tables; everything else lives in `docs`. */
const FILES = [
  { name: "catalogue.json",     origin: "catalogue", lists: ["series", "lessons"], meta: "catalogue.meta" },
  { name: "data/library.json",  origin: "library",   lists: ["series", "lessons", "books"] },
  { name: "data/makkah.json",   origin: "makkah",    lists: ["series", "lessons"] },
  { name: "data/haram.json",    origin: "haram",     lists: ["series", "lessons"] },
  { name: "data/media.json",    map: true },
  { name: "data/schedule.json", doc: "schedule" },
  { name: "data/bio.json",      doc: "bio" },
];
const TABLE = { series: "series", lessons: "lessons", books: "books" };

const q = v => v == null ? "NULL" : typeof v === "number" ? String(v) : "'" + String(v).replace(/'/g, "''") + "'";
const js = v => JSON.stringify(v);
const int = v => Number.isInteger(v) ? v : null;

function layout(text) {                       // how the file was written: indent width (null = minified) and trailing newline
  const m = /^\{\r?\n( +)"/.exec(text);   // files checked out on Windows may have CRLF line ends
  return { indent: m ? m[1].length : null, nl: text.endsWith("\n") ? 1 : 0 };
}
const render = (obj, f) => JSON.stringify(obj, null, f.indent ?? undefined) + (f.trailing_nl ? "\n" : "");

/* ---------- seed ---------- */
export function seedSql(siteDir) {
  const out = [];
  const insert = (table, cols, rows) => {                       // batches stay far below D1's 100 KB-per-statement limit
    let batch = [], size = 0;
    const flush = () => { if (batch.length) out.push(`INSERT INTO ${table} (${cols.join(",")}) VALUES\n${batch.join(",\n")};`); batch = []; size = 0; };
    for (const r of rows) {
      const v = "(" + r.map(q).join(",") + ")";
      if (size + v.length > 30000) flush();
      batch.push(v); size += v.length;
    }
    flush();
  };
  out.push("-- generated by scripts/db.mjs seed; clears and refills the content tables (users and audit_log are NOT touched)");
  for (const t of ["series", "lessons", "books", "media", "docs", "files"]) out.push(`DELETE FROM ${t};`);
  const rows = { series: [], lessons: [], books: [], media: [], docs: [], files: [] };
  for (const f of FILES) {
    const file = path.join(siteDir, f.name);
    if (!fs.existsSync(file)) continue;
    const text = fs.readFileSync(file, "utf8"), obj = JSON.parse(text), lay = layout(text);
    rows.files.push([f.name, lay.indent, lay.nl, js(f.map || f.doc ? [] : Object.keys(obj))]);   // key order only matters for files made of lists
    if (f.map) {
      Object.entries(obj).forEach(([src, v], i) => rows.media.push([src, i, js(v)]));
    } else if (f.doc) {
      rows.docs.push([f.doc, js(obj)]);
    } else {
      const meta = {};
      for (const k of Object.keys(obj)) if (!f.lists.includes(k)) meta[k] = obj[k];
      if (f.meta) rows.docs.push([f.meta, js(meta)]);
      else if (Object.keys(meta).length) throw new Error(`${f.name}: unexpected top-level keys ${Object.keys(meta)}`);
      (obj.series || []).forEach((s, i) => rows.series.push([s.id, f.origin, i, s.sec ?? null, s.title ?? "", "published", js(s)]));
      (obj.lessons || []).forEach((l, i) => rows.lessons.push([l.id, f.origin, i, l.series ?? null, l.kind ?? (f.origin === "catalogue" ? "video" : null), int(l.n), l.section ?? null, "published", js(l)]));
      (obj.books || []).forEach((b, i) => rows.books.push([b.id, f.origin, i, b.title ?? "", "published", js(b)]));
    }
  }
  insert("series", ["id", "origin", "pos", "sec", "title", "status", "data"], rows.series);
  insert("lessons", ["id", "origin", "pos", "series_id", "kind", "n", "section", "status", "data"], rows.lessons);
  insert("books", ["id", "origin", "pos", "title", "status", "data"], rows.books);
  insert("media", ["src", "pos", "data"], rows.media);
  insert("docs", ["name", "data"], rows.docs);
  insert("files", ["name", "indent", "trailing_nl", "keys"], rows.files);
  return out.join("\n") + "\n";
}

/* ---------- export ---------- */
export function exportFiles(db, outDir, { all = false } = {}) {
  const written = [];
  const where = all ? "" : "WHERE status = 'published'";
  const get = (sql, ...a) => db.prepare(sql).all(...a);
  const docs = Object.fromEntries(get("SELECT name, data FROM docs").map(r => [r.name, JSON.parse(r.data)]));
  const lay = Object.fromEntries(get("SELECT * FROM files").map(r => [r.name, r]));
  for (const f of FILES) {
    const l = lay[f.name];
    if (!l) continue;                                                        // file did not exist in the seed
    const keys = JSON.parse(l.keys);
    let obj;
    if (f.map) obj = Object.fromEntries(get("SELECT src, data FROM media ORDER BY pos").map(r => [r.src, JSON.parse(r.data)]));
    else if (f.doc) obj = docs[f.doc];
    else {
      const meta = f.meta ? docs[f.meta] : {};
      obj = {};
      for (const k of keys) obj[k] = f.lists.includes(k)
        ? get(`SELECT data FROM ${TABLE[k]} ${where ? where + " AND" : "WHERE"} origin = ? ORDER BY pos`, f.origin).map(r => JSON.parse(r.data))
        : meta[k];
    }
    const file = path.join(outDir, f.name);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, render(obj, l));
    written.push(f.name);
  }
  return written;
}

/* ---------- plumbing ---------- */
function scratchDb() {
  const db = new DatabaseSync(":memory:");
  for (const m of fs.readdirSync(MIGRATIONS).filter(x => x.endsWith(".sql")).sort()) db.exec(fs.readFileSync(path.join(MIGRATIONS, m), "utf8"));
  return db;
}
const arg = (name, dflt) => { const i = process.argv.indexOf("--" + name); return i < 0 ? dflt : process.argv[i + 1]; };
const flag = name => process.argv.includes("--" + name);

function verify(siteDir) {
  const db = scratchDb();
  db.exec(seedSql(siteDir));
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "dbverify-"));
  const written = exportFiles(db, tmp);
  let bad = 0;
  for (const name of written) {
    const a = Buffer.from(fs.readFileSync(path.join(siteDir, name), "utf8").replace(/\r\n/g, "\n")), b = fs.readFileSync(path.join(tmp, name));   // a Windows checkout may have CRLF: line ends are not content
    const same = a.equals(b);
    if (!same) bad++;
    console.log(`${same ? "ok  " : "DIFF"} ${name} (${a.length} bytes)`);
  }
  const c = t => db.prepare(`SELECT COUNT(*) n FROM ${t}`).get().n;
  console.log(`rows: series ${c("series")}, lessons ${c("lessons")}, books ${c("books")}, media ${c("media")}, docs ${c("docs")}`);
  fs.rmSync(tmp, { recursive: true, force: true });
  if (bad || written.length !== FILES.filter(f => fs.existsSync(path.join(siteDir, f.name))).length) { console.error(`!! ${bad} file(s) differ`); process.exit(1); }
  console.log("parity ok: the database reproduces every data file byte for byte");
}

const cmd = process.argv[2];
if (cmd === "seed") {
  const site = path.resolve(arg("site", path.join(ROOT, "site"))), out = path.resolve(arg("out", path.join(ROOT, "db", "seed.sql")));
  const sql = seedSql(site); fs.writeFileSync(out, sql);
  console.log(`wrote ${out} (${(sql.length / 1e6).toFixed(2)} MB, ${sql.split("\nINSERT").length - 1} INSERT statements)`);
} else if (cmd === "export") {
  const outDir = arg("out"); if (!outDir) { console.error("--out DIR is required"); process.exit(2); }
  let db;
  if (arg("db")) db = new DatabaseSync(arg("db"), { readOnly: true });
  else if (arg("from-sql")) { db = new DatabaseSync(":memory:"); db.exec(fs.readFileSync(arg("from-sql"), "utf8")); }
  else { console.error("give --db file.sqlite or --from-sql dump.sql"); process.exit(2); }
  const w = exportFiles(db, path.resolve(outDir), { all: flag("all") });
  console.log(`wrote ${w.length} files to ${outDir}: ${w.join(", ")}`);
} else if (cmd === "verify") {
  verify(path.resolve(arg("site", path.join(ROOT, "site"))));
} else {
  console.error("usage: node scripts/db.mjs seed | export | verify   (see the header of this file)");
  process.exit(2);
}
